"""Circom backend.

Emits a Circom 2 circuit that mirrors the *optimized* Proof IR. The generated
``@Main`` component declares exactly the public/private signals that survived
dead-constraint elimination, so the emitted artifact reflects the declared
proof intent rather than the whole network.

A companion ``constraints.json`` is written for the witness/proof simulator in
:mod:`proofintent.runtime`.
"""

from __future__ import annotations

import json
import os

from ..compiler import CompilationResult
from ..ml_ir import MLModule, MLOp
from ..proof_ir import ProofModule


def _signal_size(ml: MLModule, name: str) -> int:
    for n, size in ml.inputs:
        if n == name:
            return size
    op = ml.op_by_output(name)
    if op is not None:
        return int(op.attrs.get("out", op.attrs.get("n_out", 1)))
    for n, size in ml.outputs:
        if n == name:
            return size
    return 1


def _used_kinds(proof: ProofModule) -> set[str]:
    return {c.kind for c in proof.constraints}


def generate_circom(spec, ml: MLModule, proof: ProofModule) -> str:
    used = _used_kinds(proof)
    L: list[str] = []
    L.append("pragma circom 2.0.0;")
    L.append("")
    L.append("// Auto-generated by ProofIntent-ML")
    L.append(f"// model: {ml.name}")
    L.append(f"// public signals : {', '.join(s.name for s in proof.public_signals())}")
    L.append(f"// private signals: {', '.join(s.name for s in proof.private_signals())}")
    L.append(f"// intents        : {', '.join(i.kind for i in proof.intents)}")
    L.append("")

    # -- templates ---------------------------------------------------------
    if "dense" in used:
        L += [
            "template Dense(nIn, nOut) {",
            "    signal input  x[nIn];",
            "    signal input  w[nOut][nIn];",
            "    signal input  b[nOut];",
            "    signal output y[nOut];",
            "    signal partial[nOut][nIn + 1];",
            "    for (var i = 0; i < nOut; i++) {",
            "        partial[i][0] <== b[i];",
            "        for (var j = 0; j < nIn; j++) {",
            "            partial[i][j + 1] <== partial[i][j] + w[i][j] * x[j];",
            "        }",
            "        y[i] <== partial[i][nIn];",
            "    }",
            "}",
            "",
        ]
    if "relu" in used:
        L += [
            "// Fixed-point ReLU. Each unit is booleanized once; a full",
            "// deployment must add the shared saturation range check from",
            "// circomlib for soundness.",
            "template ReLU(n) {",
            "    signal input  x[n];",
            "    signal output y[n];",
            "    signal s[n];",
            "    for (var i = 0; i < n; i++) {",
            "        s[i] <-- (x[i] >= 0) ? 1 : 0;",
            "        s[i] * (s[i] - 1) === 0;",
            "        y[i] <== s[i] * x[i];",
            "    }",
            "}",
            "",
        ]
    if "argmax" in used:
        L += [
            "template ArgMax(n) {",
            "    signal input  x[n];",
            "    signal output y;",
            "    signal best[n];",
            "    signal idx[n];",
            "    signal take[n];",
            "    best[0] <== x[0];",
            "    idx[0]  <== 0;",
            "    for (var i = 1; i < n; i++) {",
            "        take[i] <-- (x[i] > best[i - 1]) ? 1 : 0;",
            "        take[i] * (take[i] - 1) === 0;",
            "        best[i] <== take[i] * (x[i] - best[i - 1]) + best[i - 1];",
            "        idx[i]  <== take[i] * (i - idx[i - 1]) + idx[i - 1];",
            "    }",
            "    y <== idx[n - 1];",
            "}",
            "",
        ]
    if "softmax" in used:
        L += [
            "template Confidence(n) {",
            "    signal input  x[n];",
            "    signal output y;",
            "    signal expx[n];",
            "    signal cum[n + 1];",
            "    cum[0] <== 0;",
            "    for (var i = 0; i < n; i++) {",
            "        expx[i] <-- Exp2Approx(x[i]);",
            "        cum[i + 1] <== cum[i] + expx[i];",
            "    }",
            "    var maxi = 0;",
            "    for (var i = 1; i < n; i++) { if (x[i] > x[maxi]) { maxi = i; } }",
            "    y <== expx[maxi] / cum[n];",
            "}",
            "",
        ]
    if "range" in used:
        L += [
            "template RangeCheck(n, lo, hi) {",
            "    signal input x[n];",
            "    signal output ok;",
            "    signal lower[n];",
            "    signal upper[n];",
            "    signal cum[n + 1];",
            "    cum[0] <== 1;",
            "    for (var i = 0; i < n; i++) {",
            "        lower[i] <-- (x[i] >= lo) ? 1 : 0;",
            "        upper[i] <-- (x[i] <= hi) ? 1 : 0;",
            "        lower[i] * (lower[i] - 1) === 0;",
            "        upper[i] * (upper[i] - 1) === 0;",
            "        cum[i + 1] <== cum[i] * lower[i] * upper[i];",
            "    }",
            "    ok <== cum[n];",
            "}",
            "",
        ]

    # -- Main --------------------------------------------------------------
    L.append("template Main() {")
    for name, size in ml.inputs:
        L.append(f"    signal input {name}[{size}];")
    for op in ml.ops:
        if op.op == "dense":
            n_in = int(op.attrs.get("in", 0))
            n_out = int(op.attrs.get("out", 0))
            L.append(f"    signal input {op.output}_W[{n_out}][{n_in}];")
            L.append(f"    signal input {op.output}_b[{n_out}];")
    for op in ml.ops:
        if op.op in ("dense", "relu"):
            n_out = int(op.attrs.get("out", op.attrs.get("n_out", 0)))
            if n_out:
                L.append(f"    signal {op.output}[{n_out}];")
            else:
                L.append(f"    signal {op.output};")
        elif op.op in ("argmax", "const"):
            L.append(f"    signal {op.output};")

    class_out = next((d for d in spec.outputs.values() if d.kind == "class"), None)
    tensor_outs = [d for d in spec.outputs.values() if d.kind != "class"]
    if class_out is not None:
        L.append("    signal output y;")
    for d in tensor_outs:
        L.append(f"    signal output {d.name}[{d.size}];")
    if "range" in used:
        for c in proof.constraints:
            if c.kind == "range":
                name = c.inputs[0]
                size = _signal_size(ml, name)
                L.append(f"    signal {name}_range_ok;")
    L.append("    signal model_commit;")
    if "softmax" in used:
        L.append("    signal confidence_ok;")
    L.append("")

    # components / wiring
    prev = ml.inputs[0][0] if ml.inputs else "x"
    for op in ml.ops:
        if op.op == "dense":
            n_in = int(op.attrs.get("in", 0))
            n_out = int(op.attrs.get("out", 0))
            L.append(f"    component {op.output}_d = Dense({n_in}, {n_out});")
            for j in range(n_in):
                L.append(f"    {op.output}_d.x[{j}] <== {prev}[{j}];")
            for r in range(n_out):
                L.append(f"    {op.output}_d.b[{r}] <== {op.output}_b[{r}];")
                for cc in range(n_in):
                    L.append(
                        f"    {op.output}_d.w[{r}][{cc}] <== {op.output}_W[{r}][{cc}];"
                    )
            for k in range(n_out):
                L.append(f"    {op.output}[{k}] <== {op.output}_d.y[{k}];")
            prev = op.output
        elif op.op == "relu":
            n = int(op.attrs.get("n_out", _signal_size(ml, prev)))
            L.append(f"    component {op.output}_r = ReLU({n});")
            for k in range(n):
                L.append(f"    {op.output}_r.x[{k}] <== {prev}[{k}];")
                L.append(f"    {op.output}[{k}] <== {op.output}_r.y[{k}];")
            prev = op.output
        elif op.op == "argmax":
            n = int(op.attrs.get("n_out", _signal_size(ml, prev)))
            L.append(f"    component {op.output}_a = ArgMax({n});")
            for k in range(n):
                L.append(f"    {op.output}_a.x[{k}] <== {prev}[{k}];")
            L.append(f"    {op.output} <== {op.output}_a.y;")
            prev = op.output
        elif op.op == "const":
            L.append(f"    {op.output} <== 0;")
            prev = op.output
        L.append("")

    if "softmax" in used:
        logits = prev
        for c in proof.constraints:
            if c.kind == "softmax":
                logits = c.inputs[0]
                break
        n_classes = int(next((c.meta.get("n_out", 1) for c in proof.constraints if c.kind == "softmax"), 1))
        L.append(f"    component confidence = Confidence({n_classes});")
        for k in range(n_classes):
            L.append(f"    confidence.x[{k}] <== {logits}[{k}];")
        L.append("    confidence_ok <== confidence.y;")
        L.append("")

    if "range" in used:
        for c in proof.constraints:
            if c.kind != "range":
                continue
            name = c.inputs[0]
            size = int(c.meta.get("n_elems", _signal_size(ml, name)))
            lo = c.meta.get("low", 0)
            hi = c.meta.get("high", 0)
            L.append(f"    component range_{name} = RangeCheck({size}, {lo}, {hi});")
            for k in range(size):
                L.append(f"    range_{name}.x[{k}] <== {name}[{k}];")
            L.append(f"    {name}_range_ok <== range_{name}.ok;")
            L.append("")

    # model commitment hook
    L.append("    // Model commitment: replace with a Poseidon hash of the parameters")
    L.append("    // in a full deployment. Kept as a public binding signal here.")
    L.append("    model_commit <== 1;")
    L.append("")

    # output wiring
    if class_out is not None:
        L.append(f"    y <== {prev};")
    if tensor_outs:
        src = prev
        for d in tensor_outs:
            for k in range(d.size):
                L.append(f"    {d.name}[{k}] <== {src}[{k}];")

    L.append("}")
    L.append("")

    # -- main component with public signal list ----------------------------
    public = [s.name for s in proof.public_signals()]
    # output signals are public by construction
    if class_out is not None and "y" not in public:
        public.append("y")
    for d in tensor_outs:
        if d.name not in public:
            public.append(d.name)
    if "model_commit" not in public:
        public.append("model_commit")
    L.append("component main {public [" + ", ".join(public) + "]} = Main();")
    L.append("")
    return "\n".join(L)


def emit_circom(result: CompilationResult, outdir: str) -> dict:
    os.makedirs(outdir, exist_ok=True)

    circom_src = generate_circom(result.spec, result.ml, result.optimized)
    circom_path = os.path.join(outdir, "circuit.circom")
    with open(circom_path, "w", encoding="utf-8") as fh:
        fh.write(circom_src)

    proof_path = os.path.join(outdir, "proof_ir.json")
    with open(proof_path, "w", encoding="utf-8") as fh:
        json.dump(result.optimized.to_dict(), fh, indent=2)

    baseline_path = os.path.join(outdir, "proof_ir.baseline.json")
    with open(baseline_path, "w", encoding="utf-8") as fh:
        json.dump(result.baseline.to_dict(), fh, indent=2)

    ml_path = os.path.join(outdir, "ml_ir.json")
    with open(ml_path, "w", encoding="utf-8") as fh:
        json.dump(result.ml.to_dict(), fh, indent=2)

    manifest = {
        "model": result.ml.name,
        "public_signals": [s.name for s in result.optimized.public_signals()],
        "private_signals": [s.name for s in result.optimized.private_signals()],
        "intents": [i.to_dict() for i in result.optimized.intents],
        "metrics": result.metrics(),
    }
    manifest_path = os.path.join(outdir, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)

    return {
        "circom": circom_path,
        "proof_ir": proof_path,
        "proof_ir_baseline": baseline_path,
        "ml_ir": ml_path,
        "manifest": manifest_path,
    }
